export interface ModelMetadata {
  successed?: boolean;
  isOpen?: boolean;
  organization?: string;
}

export type FilterStrategy = "showAll" | "hideDeprecated" | "hideOld" | "onePerOrg";

export function getFilterDescription(strategy: FilterStrategy): string {
  switch (strategy) {
    case "showAll":
      return "Never";
    case "hideDeprecated":
      return "Drop deprecated";
    case "hideOld":
      return "Drop old";
    case "onePerOrg":
      return "Best / org";
  }
}

export function shouldShowModel(
  model: string,
  metadata: ModelMetadata,
  strategy: FilterStrategy,
  allModels: Array<{ name: string; rating: number }>,
): boolean {
  switch (strategy) {
    case "showAll":
      return true;
    case "hideDeprecated":
      return !metadata.successed;
    case "hideOld":
      return true; // todo: implement this once cost data is in
    case "onePerOrg":
      if (!metadata.organization) return true;
      const orgModels = allModels.filter(
        (m) => modelMetadata[m.name]?.organization === metadata.organization,
      );
      const bestOrgModel = orgModels.reduce((best, current) =>
        current.rating > best.rating ? current : best,
      );
      return bestOrgModel.name === model;
  }
}

// Add organization info to metadata
export const modelMetadata: Record<string, ModelMetadata> = {
  "athene-70b-0725": { isOpen: true, organization: "NexusFlow" },
  "athene-v2-chat": { isOpen: true, organization: "NexusFlow" },
  "amazon-nova-pro-v1.0": { organization: "Amazon" },
  "amazon-nova-lite-v1.0": { organization: "Amazon" },
  "amazon-nova-micro-v1.0": { organization: "Amazon" },
  "bard-jan-24-gemini-pro": { organization: "Google" },
  "c4ai-aya-expanse-32b": { isOpen: true, organization: "Cohere" },
  "c4ai-aya-expanse-8b": { isOpen: true, organization: "Cohere" },
  "chatglm-6b": { isOpen: true },
  "chatglm2-6b": { isOpen: true },
  "chatglm3-6b": { isOpen: true },
  "glm-4-plus": { organization: "Zhipu" },
  "glm-4-0116": { organization: "Zhipu" },
  "glm-4-0520": { organization: "Zhipu" },
  "mistral-medium": { organization: "Mistral" },
  "mistral-next": { organization: "Mistral" },
  "chatgpt-4o-latest-20241120": { organization: "OpenAI" },
  "chatgpt-4o-latest-20240808": { successed: true, organization: "OpenAI" },
  "chatgpt-4o-latest-20240903": { successed: true, organization: "OpenAI" },
  "claude-3-5-sonnet-20241022": { organization: "Anthropic" },
  "claude-3-opus-20240229": { organization: "Anthropic" },
  "claude-3-5-haiku-20241022": { organization: "Anthropic" },
  "claude-3-5-sonnet-20240620": { organization: "Anthropic" },
  "claude-3-sonnet-20240229": { organization: "Anthropic" },
  "claude-3-haiku-20240307": { organization: "Anthropic" },
  "claude-instant-1": { organization: "Anthropic" },
  "claude-1": { organization: "Anthropic" },
  "claude-2.0": { organization: "Anthropic" },
  "claude-2.1": { organization: "Anthropic" },
  "codellama-34b-instruct": { isOpen: true },
  "codellama-70b-instruct": { isOpen: true },
  "command-r": { isOpen: true, organization: "Cohere" },
  "command-r-08-2024": { isOpen: true, organization: "Cohere" },
  "command-r-plus": { isOpen: true, organization: "Cohere" },
  "command-r-plus-08-2024": { isOpen: true, organization: "Cohere" },
  "dbrx-instruct-preview": { isOpen: true },
  "palm-2": { organization: "Google" },
  "deepseek-coder-v2": { isOpen: true, organization: "DeepSeek" },
  "deepseek-coder-v2-0724": { isOpen: true, organization: "DeepSeek" },
  "deepseek-llm-67b-chat": { isOpen: true, organization: "DeepSeek" },
  "deepseek-v2-api-0628": { isOpen: true, organization: "DeepSeek" },
  "deepseek-v2.5": { isOpen: true, organization: "DeepSeek" },
  "deepseek-v2.5-1210": { isOpen: true, organization: "DeepSeek" },
  "dolly-v2-12b": { isOpen: true },
  "falcon-180b-chat": { isOpen: true },
  "fastchat-t5-3b": { isOpen: true },
  "gemini-1.5-flash-001": { organization: "Google" },
  "gemini-1.5-flash-002": { organization: "Google" },
  "gemini-1.5-flash-8b-exp-0827": { successed: true, organization: "Google" },
  "gemini-1.5-flash-exp-0827": { successed: true, organization: "Google" },
  "gemini-1.5-pro-001": { organization: "Google" },
  "gemini-1.5-pro-002": { organization: "Google" },
  "gemini-1.5-pro-api-0409-preview": { successed: true, organization: "Google" },
  "gemini-1.5-pro-exp-0801": { successed: true, organization: "Google" },
  "gemini-1.5-pro-exp-0827": { successed: true, organization: "Google" },
  "gemini-1.5-flash-8b-001": { organization: "Google" },
  "gemini-2.0-flash-thinking-exp-1219": { organization: "Google" },
  "gemini-2.0-flash-exp": { organization: "Google" },
  "gemini-advanced-0514": { organization: "Google" },
  "gemini-exp-1206": { organization: "Google" },
  "gemini-exp-1114": { successed: true, organization: "Google" },
  "gemini-exp-1121": { successed: true, organization: "Google" },
  "gemini-pro": { organization: "Google" },
  "gemini-pro-dev-api": { organization: "Google" },
  "gemma-1.1-2b-it": { isOpen: true, organization: "Google Open" },
  "gemma-1.1-7b-it": { isOpen: true, organization: "Google Open" },
  "gemma-2-27b-it": { isOpen: true, organization: "Google Open" },
  "gemma-2-2b-it": { isOpen: true, organization: "Google Open" },
  "gemma-2-9b-it": { isOpen: true, organization: "Google Open" },
  "gemma-2-9b-it-simpo": { isOpen: true, organization: "Google Open" },
  "gemma-2b-it": { isOpen: true, organization: "Google Open" },
  "gemma-7b-it": { isOpen: true, organization: "Google Open" },
  "gpt-3.5-turbo-0314": { organization: "OpenAI" },
  "gpt-3.5-turbo-0613": { organization: "OpenAI" },
  "gpt-3.5-turbo-0125": { organization: "OpenAI" },
  "gpt-3.5-turbo-1106": { organization: "OpenAI" },
  "gpt-4-0314": { organization: "OpenAI" },
  "gpt-4-1106-preview": { organization: "OpenAI" },
  "gpt-4o-2024-05-13": { organization: "OpenAI" },
  "gpt-4o-2024-08-06": { organization: "OpenAI" },
  "gpt-4o-mini-2024-07-18": { organization: "OpenAI" },
  "gpt-4-turbo-2024-04-09": { organization: "OpenAI" },
  "gpt-4-0125-preview": { organization: "OpenAI" },
  "gpt-4-0613": { organization: "OpenAI" },
  "gpt4all-13b-snoozy": { isOpen: true },
  "granite-3.0-2b-instruct": { isOpen: true },
  "granite-3.0-8b-instruct": { isOpen: true },
  "guanaco-33b": { isOpen: true },
  "grok-2-2024-08-13": { organization: "xAI" },
  "grok-2-mini-2024-08-13": { organization: "xAI" },
  "internlm2_5-20b-chat": { isOpen: true },
  "internvl2-26b": { isOpen: true },
  "internvl2-4b": { isOpen: true },
  "jamba-1.5-large": { isOpen: true, organization: "AI21" },
  "jamba-1.5-mini": { isOpen: true, organization: "AI21" },
  "koala-13b": { isOpen: true },
  "llama-13b": { isOpen: true, organization: "Meta" },
  "llama2-70b-steerlm-chat": { isOpen: true, organization: "NVIDIA" },
  "llama-2-13b-chat": { isOpen: true, organization: "Meta" },
  "llama-2-70b-chat": { isOpen: true, organization: "Meta" },
  "llama-2-7b-chat": { isOpen: true, organization: "Meta" },
  "llama-3-70b-instruct": { isOpen: true, organization: "Meta" },
  "llama-3-8b-instruct": { isOpen: true, organization: "Meta" },
  "llama-3.1-405b-instruct-bf16": { isOpen: true, organization: "Meta" },
  "llama-3.1-405b-instruct-fp8": { isOpen: true, organization: "Meta" },
  "llama-3.1-70b-instruct": { isOpen: true, organization: "Meta" },
  "llama-3.1-8b-instruct": { isOpen: true, organization: "Meta" },
  "llama-3.1-nemotron-51b-instruct": { isOpen: true, organization: "NVIDIA" },
  "llama-3.1-nemotron-70b-instruct": { isOpen: true, organization: "NVIDIA" },
  "llama-3.2-1b-instruct": { isOpen: true, organization: "Meta" },
  "llama-3.2-3b-instruct": { isOpen: true, organization: "Meta" },
  "llama-3.2-vision-11b-instruct": { isOpen: true, organization: "Meta" },
  "llama-3.2-vision-90b-instruct": { isOpen: true, organization: "Meta" },
  "llama-3.3-70b-instruct": { isOpen: true, organization: "Meta" },
  "llava-v1.6-34b": { isOpen: true },
  "minicpm-v-2_6": { isOpen: true },
  "ministral-8b-2410": { isOpen: true, organization: "Mistral" },
  "mistral-7b-instruct": { isOpen: true, organization: "Mistral" },
  "mistral-7b-instruct-v0.2": { isOpen: true, organization: "Mistral" },
  "mistral-large-2402": { organization: "Mistral" },
  "mistral-large-2407": { organization: "Mistral" },
  "mistral-large-2411": { isOpen: true, organization: "Mistral" },
  "mixtral-8x22b-instruct-v0.1": { isOpen: true, organization: "Mistral" },
  "mixtral-8x7b-instruct-v0.1": { isOpen: true, organization: "Mistral" },
  "molmo-72b-0924": { isOpen: true, organization: "Allen" },
  "molmo-7b-d-0924": { isOpen: true, organization: "Allen" },
  "mpt-30b-chat": { isOpen: true },
  "mpt-7b-chat": { isOpen: true },
  "nemotron-4-340b-instruct": { isOpen: true, organization: "NVIDIA" },
  "nous-hermes-2-mixtral-8x7b-dpo": { isOpen: true },
  "o1-preview": { organization: "OpenAI" },
  "o1-mini": { organization: "OpenAI" },
  "oasst-pythia-12b": { isOpen: true },
  "olmo-7b-instruct": { isOpen: true },
  "openchat-3.5": { isOpen: true },
  "openchat-3.5-0106": { isOpen: true },
  "openhermes-2.5-mistral-7b": { isOpen: true },
  "phi-3-medium-4k-instruct": { isOpen: true, organization: "Microsoft" },
  "phi-3-mini-128k-instruct": { isOpen: true, organization: "Microsoft" },
  "phi-3-mini-4k-instruct": { isOpen: true, organization: "Microsoft" },
  "phi-3-mini-4k-instruct-june-2024": { isOpen: true, organization: "Microsoft" },
  "phi-3-small-8k-instruct": { isOpen: true, organization: "Microsoft" },
  "phi-3-vision-128k-instruct": { isOpen: true, organization: "Microsoft" },
  "phi-3.5-vision-instruct": { isOpen: true, organization: "Microsoft" },
  "pixtral-12b-2409": { isOpen: true, organization: "Mistral" },
  "pixtral-large-2411": { isOpen: true, organization: "Mistral" },
  "qwen-14b-chat": { isOpen: true, organization: "Qwen" },
  "qwen1.5-110b-chat": { isOpen: true, organization: "Qwen" },
  "qwen1.5-14b-chat": { isOpen: true, organization: "Qwen" },
  "qwen1.5-32b-chat": { isOpen: true, organization: "Qwen" },
  "qwen1.5-4b-chat": { isOpen: true, organization: "Qwen" },
  "qwen1.5-72b-chat": { isOpen: true, organization: "Qwen" },
  "qwen1.5-7b-chat": { isOpen: true, organization: "Qwen" },
  "qwen2-72b-instruct": { isOpen: true, organization: "Qwen" },
  "qwen2-vl-72b": { isOpen: true, organization: "Qwen" },
  "qwen2-vl-7b-instruct": { isOpen: true, organization: "Qwen" },
  "qwen2.5-72b-instruct": { isOpen: true, organization: "Qwen" },
  "qwen2.5-coder-32b-instruct": { isOpen: true, organization: "Qwen" },
  "qwen-max-0919": { organization: "Qwen" },
  "qwen2.5-plus-1127": { organization: "Qwen" },
  "qwen-plus-0828": { organization: "Qwen" },
  "qwen-max-0428": { organization: "Qwen" },
  "qwen-vl-max-1119": { organization: "Qwen" },
  "qwq-32b-preview": { isOpen: true, organization: "Qwen" },
  "reka-core-20240501": { successed: true, organization: "Reka AI" },
  "reka-core-20240722": { successed: true, organization: "Reka AI" },
  "reka-core-20240904": { organization: "Reka AI" },
  "reka-flash-preview-20240611": { successed: true, organization: "Reka AI" },
  "reka-flash-20240722": { successed: true, organization: "Reka AI" },
  "reka-flash-20240904": { organization: "Reka AI" },
  "reka-flash-21b-20240226-online": { organization: "Reka AI" },
  "reka-flash-21b-20240226": { organization: "Reka AI" },
  "RWKV-4-Raven-14B": { isOpen: true },
  "snowflake-arctic-instruct": { isOpen: true },
  "stablelm-tuned-alpha-7b": { isOpen: true },
  "starling-lm-7b-alpha": { isOpen: true },
  "starling-lm-7b-beta": { isOpen: true },
  "stripedhyena-nous-7b": { isOpen: true },
  "vicuna-13b": { isOpen: true },
  "vicuna-33b": { isOpen: true },
  "vicuna-7b": { isOpen: true },
  "wizardlm-13b": { isOpen: true },
  "wizardlm-70b": { isOpen: true },
  "yi-1.5-34b-chat": { isOpen: true, organization: "01" },
  "yi-34b-chat": { isOpen: true, organization: "01" },
  "yi-lightning": { organization: "01" },
  "yi-lightning-lite": { organization: "01" },
  "yi-large-preview": { organization: "01" },
  "yi-large": { organization: "01" },
  "zephyr-7b-alpha": { isOpen: true },
  "zephyr-7b-beta": { isOpen: true },
  "zephyr-orpo-141b-A35b-v0.1": { isOpen: true },
} as const;
